name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "47 4 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
